# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 55b74edf7a3a8306112b83a699c52cf964039454d971c97f31bbe3b57a29565585c9bc95ccc57a431972b193f51afbd46f92ac0dbb89a758681fb4bd8b453cac

test:
  secret_key_base: 4e7edf77ff67cc49c0cc80049e368efcec00084372b75151f12c096a3120f1f9a03abb528223e7bf4f10bde188c5bf4d98e6ffe2b6f43a2ae7dc2db3b95c5f16

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
